---
title: Statistica A
categories: ["Didattica"]
description: ["Contenuti didattici"]
tags: ["Didattica", "Statistica A"]
output: 
  flexdashboard::flex_dashboard:
    storyboard: TRUE
---

# Programma

### Informazioni generali sul corso

Il corso si svolgerà ad anni alterni, quindi A.A. 2017-2018, 2019-2020, etc

---

### Breve introduzione al corso

L’approccio bayesiano all’inferenza sta acquisendo sempre più importanza in vari ambiti della statistica. Il fine del corso è quello di introdurre l’approccio bayesiano ai problemi di inferenza statistica parametrica. Gli argomenti trattati nel corso sono argomenti standard per l’approccio bayesiano alla statistica, per questo motivo si trovano una moltitudine di testi che coprono l’intero programma del corso (e molto altro). Nel corso verranno trattati argomenti che si possono trovare su più testi, tra questi quelli che meglio si adattano al programma ed all’approccio del corso sono il libro di Hoff (2009) e quello di Kruschke (2010), per quanto riguarda la parte modellistica e applicata dell’analisi statistica, mentre per quella teorica si farà riferimento a Ghosh et al. Oltre a questi testi, per eventuali approfondimenti sono molto interessanti il Bernardo and Smith (1994), che analizza in modo abbastanza rigoroso l’approccio inferenziale bayesiano e Gelman et al. (2004) per una introduzione all’analisi dei dati bayesiana. Per una trattazione rigorosa, generale e più approfondita dal punto di vista della statistica matematica, non solo bayesiana, vi è lo Schervish (1995), è però necessario osservare che questo testo richiede una buona conoscenza della teoria della misura e dell’integrazione astratta. Quest’ultimo libro è molto utile per ulteriori approfondimenti. I testi di 4. e 5. a cui si farà spesso riferimento durante il corso fanno ampio uso del software statistico (gratuito) R, per questo motivo si suggerisce di installarlo per far girare i listati presenti nei testi. I link per ottenere il software si possono trovare in Risorse utili.
Prerequisiti

Prerequisito essenziale per poter seguire il corso con profitto è la padronanza degli argomenti trattati nel corso di Probabilità.

---

## Testi di consigliati

1. Bernardo, J.-M. and A. F. M. Smith (1994). Bayesian theory. Wiley Series in Probability and Mathematical Statistics, Wiley & Sons Ltd.
2. Gelman, A., J. B. Carlin, H. S. Stern, and D. B. Rubin (2004). Bayesian Data Analysis (Second ed.). Texts in Statistical Science Series. Chapman & Hall/CRC, Boca Raton, FL. 
3. Ghosh, J., M. Delampady, and T. Samanta (2006). An introduction to Bayesian analysis. Springer Texts in Statistics. New York: Springer.
4. Hoff, P. D. (2009). A first course in Bayesian statistical methods. Springer Texts in Statistics. New York: Springer.
5. Kruschke, J. K. (2010) Doing Bayesian Data Analysis. A Tutorial Introduction with R. Academic Press
6. Schervish, M. J. (1995). Theory of statistics. Springer Series in Statistics. New York: Springer-Verlag.


